name: CMake

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  call-node-workflow:
    uses: ./.github/workflows/node.js.yml

  build:
    needs: call-node-workflow
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        GP2040_BOARDCONFIG: ["Pico"]

    steps:
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: "3.31.x"

      - name: Verify cmake
        run: cmake --version

      # Global Setup
      - name: Checkout GP2040-CE
        uses: actions/checkout@v6.0.1
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: arm-none-eabi-gcc GNU Arm Embedded Toolchain
        uses: carlosperate/arm-none-eabi-gcc-action@v1.11.1

      - name: Checkout pico-sdk/2.2.0
        uses: actions/checkout@v6.0.1
        with:
          repository: raspberrypi/pico-sdk
          ref: 2.2.0
          path: pico-sdk

      - name: Checkout pico-sdk submodules
        working-directory: ${{ github.workspace }}/pico-sdk
        run: git submodule update --init

      - name: Download a Build Artifact
        uses: actions/download-artifact@v7.0.0
        with:
          name: fsData
          path: ${{ github.workspace }}/lib/httpd/

      - name: Get core count
        id: core_count
        run: cat /proc/cpuinfo | grep processor | wc -l
      # End Global Setup

      - name: Pico Build Configure CMake
        shell: bash
        run: PICO_SDK_PATH=${{ github.workspace }}/pico-sdk GP2040_BOARDCONFIG=${{ matrix.GP2040_BOARDCONFIG }} SKIP_WEBBUILD=TRUE cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

      - name: Pico Build
        shell: bash
        run: GP2040_BOARDCONFIG=${{ matrix.GP2040_BOARDCONFIG }} cmake --build ${{ github.workspace }}/build --config ${{ env.BUILD_TYPE }} --parallel ${{ steps.core_count.outputs.output }}

      - name: Upload Pico Artifact
        uses: actions/upload-artifact@v6.0.0
        with:
          name: GP2040-CE - ${{ matrix.GP2040_BOARDCONFIG }}
          path: ${{ github.workspace }}/build/GP2040-CE_*_${{ matrix.GP2040_BOARDCONFIG }}.uf2
          if-no-files-found: error

      - name: Upload .elf Artifact
        uses: actions/upload-artifact@v6.0.0
        with:
          name: elf
          path: ${{ github.workspace }}/build/GP2040-CE_*_${{ matrix.GP2040_BOARDCONFIG }}.elf
          if-no-files-found: error
